// Fictional preview scores.
window.__THEME_DATA__ = {
  generatedAt: "2026-08-27T12:00:00.000Z",
  generatorName: "Takase bot",
  profile: { playerName: "DEMO PLAYER" },
  song: {
    songId: 870,
    title: "VIIIbit Explorer",
    artist: "Lime",
    category: "チュウマイ",
    bpm: 188,
    duration: "2:19",
    releaseDate: "2023-09-14",
    version: "bright MEMORY Act.2",
    status: "online",
    jacketUrl: "https://oss-hd1.bemanicn.com/SDDT/cover/d5c720ec2006ca2f916939e8b93a8163.webp-thumbnail",
    bossName: "高瀬 梨緒",
    bossCardId: 100030,
    bossCardName: "【R】高瀬 梨緒[体操着]",
    bossLevel: 61,
    attribute: "Aqua",
  },
  charts: [
    {
      difficultyId: 0,
      difficulty: "BASIC",
      hasChart: true,
      level: "4",
      constant: 4.0,
      chartDesigner: "ものくろっく",
      noteCount: 451,
      bellCount: 37,
      personal: { played: false, techScore: null, technicalRank: null, isAllBreak: false, isFullBell: false },
    },
    {
      difficultyId: 1,
      difficulty: "ADVANCED",
      hasChart: true,
      level: "10",
      constant: 10.0,
      chartDesigner: "みそかつ侍",
      noteCount: 825,
      bellCount: 106,
      personal: { played: true, techScore: 1000000, technicalRank: "SSS", isAllBreak: true, isFullBell: true },
    },
    {
      difficultyId: 2,
      difficulty: "EXPERT",
      hasChart: true,
      level: "13",
      constant: 13.3,
      chartDesigner: "みそかつ侍",
      noteCount: 1197,
      bellCount: 126,
      personal: { played: true, techScore: 1000000, technicalRank: "SSS", isAllBreak: false, isFullBell: true },
    },
    {
      difficultyId: 3,
      difficulty: "MASTER",
      hasChart: true,
      level: "14",
      constant: 14.6,
      chartDesigner: "kawaii lemon",
      noteCount: 1658,
      bellCount: 143,
      personal: { played: true, techScore: 1000000, technicalRank: "SSS", isAllBreak: false, isFullBell: false },
    },
    {
      difficultyId: 10,
      difficulty: "LUNATIC",
      hasChart: false,
      level: null,
      constant: null,
      chartDesigner: null,
      noteCount: null,
      bellCount: null,
      personal: { played: false, techScore: null, technicalRank: null, isAllBreak: false, isFullBell: false },
    },
  ],
};
